title: Arthur Silva
logo: "assets/img/photo.png"
email: arthursilva.aasdl@gmail.com
description: >
  Graduating in Statistics at UFC 
  <br>
  Interested in Data Analysis with
  Python, SQL, Excel, Power BI and ML

remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: Kaggle
    icon: <i class="fa-brands fa-kaggle"></i>
    link: https://www.kaggle.com/arthursdelima
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/4r7hu3

#theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 -- Google Analytics tracking ID here
