title: Arthur Silva
logo: "/images/photo.png"
email: arthursilva.aasdl@gmail.com
description: >
  Graduating in Statistics at UFC 
  <br>
  Interested in Data Analysis with
  Python, SQL, Excel, Power BI and ML 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 -- Google Analytics tracking ID here

platforms:
  - name: Kaggle
    icon: <i class="fa-brands fa-kaggle"></i>
    link: https://www.kaggle.com/arthursdelima
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/4r7hu3
